name: ekaplus_ekatunggal
description: "Eka+ Ekatunggal Mobile Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.12.0
  get: ^4.7.2
  get_it: ^9.0.1
  go_router: ^16.3.0
  http: ^1.5.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  socket_io_client: ^3.1.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/fonts/
    - assets/icons/
    - assets/icons/kategori/
    - assets/images/
    - assets/images/account/
    - assets/images/items/
    - assets/images/type/
    - assets/images/banner/
    - assets/images/kategori/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
